export const LOGIN_SUCCEED = 'LOGIN_SUCCEED';
export const SET_USER = 'SET_USER';
export const LOGGED_IN_USER_FETCHED = 'LOGGED_IN_USER_FETCHED';
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_IN_STORE = 'UPDATE_USER_IN_STORE';
