export const ROOT = "/";
export const SIGNIN = "/signin";
export const SIGNUP = "/signup";
export const FORGOTPASSWORD = "/forgot-password";
export const RESETPASSWORD = "/verify-reset-password";
export const DASHBOARD = "/dashboard";
export const SAMPLEPAGE = "/samplepage";
export const UICOMPONENT = "/uicomponent";  
export const SUBJECTMANAGEMENT = "/subjectmanagement";  
export const CHAPTER = "/CHAPTER"
export const SUBJECT = "/SUBJECT"
export const GRADE = "/GRADE"
export const TOPICDETAIL = "/TOPICDETAIL" 
export const TABCHILD ="/TABCHILD"
